---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanxuewei.
--- DateTime: 2025/8/15 14:39
---

-- 比较线程标识与锁中的标识是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', key[1])
end
return 0